repos:
  - repo: local
    hooks:
      - id: lint
        language: system
        name: lint
        entry: task lint
  - repo: local
    hooks:
      - id: test
        language: system
        name: test
        entry: task test
